Missed output format
Fixed exception:

ERROR security.UserGroupInformation: PriviledgedActionException as:cloudera cause:org.apache.hadoop.mapred.InvalidJobConfException: Output directory not set.
org.apache.hadoop.mapred.InvalidJobConfException: Output directory not set.
        at org.apache.hadoop.mapreduce.lib.output.FileOutputFormat.checkOutputSpecs(FileOutputFormat.java:128)
        at org.apache.hadoop.mapred.JobClient$2.run(JobClient.java:949)
        at org.apache.hadoop.mapred.JobClient$2.run(JobClient.java:912)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:396)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1136)
        at org.apache.hadoop.mapred.JobClient.submitJobInternal(JobClient.java:912)
        at org.apache.hadoop.mapreduce.Job.submit(Job.java:500)
        at org.apache.hadoop.mapreduce.Job.waitForCompletion(Job.java:530)
        at gov.llnl.demo.CountRowsMR.run(CountRowsMR.java:80)
        at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:65)
        at gov.llnl.demo.CountRowsMR.main(CountRowsMR.java:49)

by adding job.setOutputFormatClass(NullOutputFormat.class);